### ISSUE TITLE
"New CBT Version" message does not clear after updating FILE001 and REBUILDing.

### ISSUE THREAD

**Issue by catherdersoftware** [lbdyck/CBTView#7]
After updating to V507 and REBUILDing, the "New CBT Version" message does not clear. This is confusing.

**Comment by catherdersoftware** [comment]
I just noticed that the CBTView version that I was running was V506. The update got me to V507, but CBT is currently V508. So yes it was accurate, but we should skip versions if there's more than one new version.

**Comment by lbdyck** [comment]
fixed in the 1.80 release
